# Generated by Django 4.2.3 on 2023-09-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0002_alter_practice_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.TextField()),
                ('Lastname', models.TextField()),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('DOB', models.DateTimeField()),
                ('Nationality', models.TextField()),
                ('State_Of_Origin', models.TextField()),
            ],
        ),
    ]
