# Generated by Django 4.2.3 on 2023-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0003_customer_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='apis',
            fields=[
                ('Primary_key', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.TextField()),
                ('Department', models.TextField()),
            ],
        ),
    ]
