# Generated by Django 4.2.3 on 2023-09-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0004_apis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apis',
            old_name='Primary_key',
            new_name='id',
        ),
    ]
