# Generated by Django 4.2.3 on 2023-09-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0005_rename_primary_key_apis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_data',
            name='id',
        ),
        migrations.AddField(
            model_name='customer_data',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
